# Markdown linting configuration for JarvisCluster_Development
default: true

# MD013: Line length
MD013:
  line_length: 120
  tables: false
  code_blocks: false

# MD033: Allow inline HTML (needed for complex tables)
MD033: false

# MD041: First line in file should be a top level heading
MD041: false

# MD024: Multiple headers with the same content
MD024:
  siblings_only: true
